version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/var/www
    container_name: project_app
    depends_on:
      - db
    command: sh -c "chmod -R 777 /var/www/storage && php-fpm"

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./src/tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lardocker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db